[package]
name = "riffle"
version = "0.1.0"
authors = ["David Peter <mail@david-peter.de>"]
edition = "2021"
description = "A pager-as-a-library"
license = "MIT/Apache-2.0"

[dependencies]
crossterm = "0.22"

[dev-dependencies]
bat = "0.19"

[[bin]]
name = "riffle"
path = "src/app/main.rs"
